name: Go Test
run-name: ${{ github.actor }} is testing Go code
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  DoTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go ${{matrix.go-version}}
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go-version}}
      - name: Test go
        run: go test -v ./...
